### ISSUE TITLE
Amend the Adverse effects form

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#105]
- [ ] Amend the text on the adverse effects form to read as shown on row 3 (highlighted in purple) of [this data dictionary](https://docs.google.com/spreadsheets/d/106-np911xfDGUx7RpF_GdOIER4bcMHnASCCO3dlep6A/edit#gid=380395191).

**Comment by ellykits** [comment]
Were the labels for French/Arabic also updated? Otherwise I will push the updated string for translation

**Comment by AnnieMungai** [comment]
v. 0.1.7
Looks good to me!
