### ISSUE TITLE
Implement details on the child registration data

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#11]
- [x] Include the following details on the child registration data view on the child profile.
Note! All data on this view must be read-only.  The data is collected from the child registration form. 
First name
Last name
Sex
Child DOB
Neonatal tetanus protection
Child’s birth registration number
Child's unique government ID 
Child’s home facility
Mother first name
Mother last name
Mother DOB
Mother primary phone number
Father phone number
Child home address
Village
![T26](https://user-images.githubusercontent.com/58034047/84639106-969db480-af00-11ea-98bc-464e6313112c.png)

**Comment by cafootitt** [comment]
@AnnieMungai Unless otherwise specified by Sadri, I would list the fields in exactly the same order as from the registration form. 

Let's allow Elly to assign the LOE to these tickets.

**Comment by AnnieMungai** [comment]
Debug v.0.03

The display looks good, however, the text is running over thus is hidden. Some of the fields need to be shortened as below:
ID
Child's birth registration number
Child's unique government ID
Last name
First name
Place of birth
Sex
Gestational age at birth(in weeks)
Date of birth
Home address
Village
Father last name
Father first name
Father date of birth
Father nationality
Father phone number
Mother/Caregiver last name
Mother/Caregiver first name
Mother date of birth
Mother/Caregiver nationality
Indicate Mother/caregiver nationality
Mother/Caregiver phone number
Mother Td vaccine doses
Protected at birth(PAB)
Mother received Rubella vaccine

**Comment by ellykits** [comment]
@AnnieMungai  This has now been updated. see below
![Screenshot_1594391225](https://user-images.githubusercontent.com/26865532/87165542-f7879500-c2d2-11ea-8499-e569f1d692c8.png)

**Comment by AnnieMungai** [comment]
Looks good!
