### ISSUE TITLE
Not able to view previous years reports

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-unicef-tunisia#116]
- [ ] On the coverage report, on the drop down menu at the top, previous years reports are not available. A user should be able to tap on the menu to obtain all previous years - in this case, 2020 reports should be available for viewing. 
![image](https://user-images.githubusercontent.com/58034047/107377546-26314c80-6afc-11eb-8851-951c27410dc8.png)

**Comment by ellykits** [comment]
@AnnieMungai Did you run sync before opening this page?

**Comment by AnnieMungai** [comment]
Looks good- I can see the other years reports.

I however noted an issue with trying to edit the target numbers #123
