### ISSUE TITLE
Implement card support - on the mobile client side

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#13]
- [x] On the top right hand side menu on the child's profile, add _**Report lost or damaged card**_. 

(image updated 6 Nov)
![Untitled-1](https://user-images.githubusercontent.com/1584163/98398417-f7a06300-202e-11eb-9510-3823108bdbce.png)
- In this screenshot, the pulldown text looks a little small. That could go wider if needed.
- The pulldown menu button labels should be consistently sentence case
- I think this pulldown needs [dividers](https://material.io/components/menus#anatomy) to group the options (which might also mean reordering) since that list is getting long. I haven't seen this list before, but it's unwieldy. Who has context on what all of these things do @AnnieMungai?

<hr>

- [x] Tapping on the _**Report lost or damaged card**_ will open a confirmation dialogue. 
- **Report lost or damaged card?** (Confirmation dialogue title)
- Report the child card as lost or damaged. A new card will be ordered for the child. (Confirmation dialogue message)
- Options/Action buttons: _**Report lost or damaged card**_  and _**Cancel**_.

(image updated 6 Nov)
See the example below of a confirmation dialogue: 
![report lost card](https://user-images.githubusercontent.com/1584163/98409796-7c947800-2041-11eb-99ed-b1b368686a1b.png)

- [x] Selecting _**Cancel**_ will navigate back to the child profile without making any changes
- [x] Selecting _**Report lost or damaged card**_ will close the window and an android toaster message will show: **Card reported as lost or damaged. A new card will be ordered.** It will also set the card status to **needs_card** in the child client JSON Object.  Example can be seen [here]  (https://github.com/OpenSRP/opensrp-client-unicef-tunisia/issues/55) See this issue #82 
- [x] Once a new card has been ordered, the _**Report lost or damaged card**_ option on the child profile will de-activate/ be disabled. The disabled state is greyed out. **@AnnieMungai  Roger: I think we can communicate the reason for this disabled state in a few different ways. I would like to do the easiest way. Is there someone I can talk to about this when it's being built?**
- [x] For a new child registration, the _**Report lost or damaged card**_ option is inactive/disabled. **(Roger: previous point applies for this as well)**
- [x] Scanning QR code on a child's card activates the _*Report lost or damaged card*_  option on the child profile. This applies for both new registrations and ordered cards.

**Comment by rowo** [comment]
@AnnieMungai this leans pretty heavily on the "order" language. I just want to make sure the team doesn't think the client will have an issue with it. My initial recommendation was a smaller shift where you would still use the "Report lost or damaged card" and then that changes to "Card ordered" or something like that in it's disabled state because this is a general term that can be used for new registrations.

**Comment by AnnieMungai** [comment]
@rowo I would go with **Report lost or damaged card** on the android end for the client to tap on. However, the **Order new card** language inside the confirmation dialogue works well.

**Comment by rowo** [comment]
@AnnieMungai 
- I made a few updates to the first comment. Please take a look. The wording wasn't updated in the text to what you were suggesting. I don't think it's appropriate to mix the text from interaction and the confirmation, so I changed it all to the report lost or damage language.
- Where we could introduce the order language more is in the disabled state. I'd like to talk to an engineer when they work on this to choose the easiest way to do this that still makes sense.
- On that final point, I don't believe it's scanning the card that updates the pulldown. Scanning the card changes the status. Then the status change to "Does not need card" changes the button the active. But I may be wrong.

**Comment by rowo** [comment]
Update from Nov 17

Roger to provide mockups for: 
- Updated label (no date for now)
- Label is inactive state
- If click dialog, then a toaster or snackbar (Elly to send image of how it works for adverse event)

**Comment by rowo** [comment]
@ellykits Here are images for the above:

@AnnieMungai I don't know the exactly messaging that should appear in this toaster, but I feel like it can provide some information to an unsure user about what is going on. Right now I jut put "A new card is on order and will be delivered after printing." Not sure if they know how long things typically take, but that would be nice.
![printing-toaster](https://user-images.githubusercontent.com/1584163/99757422-4cc38680-2abd-11eb-860c-43ee79a224dc.png)

![newcardonorder](https://user-images.githubusercontent.com/1584163/99757403-4503e200-2abd-11eb-9338-0c29539f4475.png)

**Comment by AnnieMungai** [comment]
@rowo right now we do not know how long things will typically take. It might become clearer with time.

**Comment by ellykits** [comment]
@rowo @AnnieMungai Following up on the UI mockup provided above, in our previous meeting, my feedback was based on the assumptions of things I thought would work but had not tried. On the contrary some are not possible unless I do custom tweaks which I do not think is necessary when there are other options. Here are my findings:

1. A disabled menu item cannot listen to any event - meaning we cannot show a Toast/Snackbar notification when the user clicks the option (unless we keep it enabled).

2. Menu item titles cannot be wrapped into 2 lines (also long text on menu is not recommended as per Material Design guideline). My initial thinking was this could be possible by using new line character on the string, however for menus, the newline character is treated as space.

> For number 2 we can can explore the option of changing the message to  **Card ordered** or something plus the date it was ordered. For number 1 we can decide whether to disable the option with the new message and no iteraction, or we can activate it to make it responsive to click events.

**Comment by ellykits** [comment]
Here is a screenshot

![Screenshot_20201120_155720](https://user-images.githubusercontent.com/26865532/99802659-221f0f80-2b49-11eb-86b4-efb9f4ad4393.png)

**Comment by AnnieMungai** [comment]
@rowo to make this text shorter, can we make the in-active text to read **New card ordered on [date card status changed]**.   @ellykits will that be short enough?

**Comment by AnnieMungai** [comment]
v0.1.5-debug

Looks great!
