### ISSUE TITLE
Preview version on Playstore broken

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-unicef-tunisia#140]
**Describe the bug**
The preview version on play store is broken. This happens when the app is cut for the Google release. The actual app before the conversion is working okay and passes QA. 
- [ ] MLS feature not showing language change
- [ ] Location hierarchy not displaying thus sync not happening.

**Timelines:** 
Go-live is on 1st Dec. 
Users are expecting a working production apk by then. 

**Technical Lead on Project**
Benjamin

**Comment by dubdabasoduba** [comment]
@AnnieMungai I am testing a small fix @ndegwamartin shared. Will get back to you with the findings

**Comment by AnnieMungai** [comment]
@dubdabasoduba @ndegwamartin I have tested the apk on playstore - the one as a tester. Here are my observations: 
1.The location hierarchy is now loading. 
2. The app is still not picking the language changes. However, it also:
- is able to change to right to left text for Arabic 
- Some forms are loading in MLS; registration form + edit, death registration+edit, adverse events, record private-sector vaccines - with a few strings not showing translations. All other forms especially the growth and immunizations are not supporting MLS 100%
- All reports are in English only.

**Comment by AnnieMungai** [comment]
This was fixed! Looks great!
