### ISSUE TITLE
Add letters on Lot number on the MAPI form

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-unicef-tunisia#143]
- [ ] Allow user to types letters and numbers when typing the Lot number in the Adverse event following immunization (MAPI) section. Only numbers can be typed at the moment.

**Comment by hamza-vd** [comment]
@AnnieMungai 
There are 2 lot number fields here.
1. Lot Number
2. Thinner lot number

Do both needs to be changed or only the first one?

![device-2021-11-22-164932](https://user-images.githubusercontent.com/70560433/142856923-adce859a-394d-45a8-8a8c-ca3ed7777001.png)

**Comment by AnnieMungai** [comment]
@hamza-vd Both of them.

**Comment by AnnieMungai** [comment]
v.0.1.24- Looks good!
