### ISSUE TITLE
Add Hepatitis A to the child vaccine schedule

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-unicef-tunisia#146]
- [ ] Add Hepatitis A to the child vaccine schedule as highlighted on [this data dictionary](https://docs.google.com/spreadsheets/d/1tYvHOu3N9n2VWqZagq0na2BEag-0G7RCvWwqgjBX2vY/edit#gid=1827223928) - row 22.

**Comment by hamza-vd** [comment]
@AnnieMungai 
Should the VHA vaccine defined in the [data-dictionary](https://docs.google.com/spreadsheets/d/1tYvHOu3N9n2VWqZagq0na2BEag-0G7RCvWwqgjBX2vY/edit#gid=1827223928) above also be added for pre-term?

**Comment by AnnieMungai** [comment]
@hamza-vd yes, it is for all babies.

**Comment by AnnieMungai** [comment]
v0.2.4
Looks good!
