### ISSUE TITLE
Daily Tallies not picking MLS

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-unicef-tunisia#151]
v.0.2.3
Daily tallies not picking French and Arabic even when the language changes. 
- Months on the 1st image
- Top bar of the 2nd image
- Month on the daily tallies drop down that shows the dates.

![Untitled presentation](https://user-images.githubusercontent.com/58034047/143225275-5c3e365b-81f5-42ab-a694-7646ed00bf0b.png)

**Comment by hamza-vd** [comment]
@AnnieMungai 
Do only the highlighted Daily Tallies label in the second image need to be translated or do the month names also need translation?

**Comment by AnnieMungai** [comment]
@hamza-vd  on the 2nd image - everything highlighted needs to pick translations.

**Comment by AnnieMungai** [comment]
v.0.2.5
Looks good!
