### ISSUE TITLE
Production QA - Android

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-unicef-tunisia#155]
- [x] Log in
- [x] Child registration and editing of registration
- [x] Child profile on child detailed and history page show correctly
- [x] Loading of vaccines on child profile, administration and editing of the vaccines. 
- [x] Recording weight and height, and making edits.
- [x] Record an adverse effect (only after immunizations are given)
- [x] Recording private-sector vaccines 
- [x] Multilanguage support - all languages are displaying correctly on the forms
- [x] Out of catchment form loads 
- [x] Advanced search - works properly. 
- [x] Daily tallies load correctly after the sync
- [x] Can generate a report and submit one.

**Comment by madrinekariuki** [comment]
@AnnieMungai 

I have tested the APK above. noted 2 issues:
1. The app is crashing when:
  a)  You login and  click on the empty bars on top next to the hamburger menu bar, then the app crashes and the user has to login again.

   b)  when user tries to take a baby's photo to add to their profile.


2. When adding a child, the Caregivers/Mothers DOB is not a mandatory field, however when it is omitted and you try to submit data an error prompt shows up.


Its good to note we have some scenarios that have not been tested yet.
 -  tests around QR scan code. 
 -  tests around cards (e.g reporting a lost/damaged card) 
 -  tests on recording vaccines for children out of the catchment areas. 
 - 
 
Testcase details can be found [here](https://ona.testrail.io/index.php?/runs/view/55&group_by=cases:section_id&group_order=asc)

**Comment by dubdabasoduba** [comment]
@madrinekariuki for 1 (a) Which user did you log in with?

**Comment by madrinekariuki** [comment]
@dubdabasoduba 

- I used `demo` I will share the Password privately if needed. 
-  I am using android version 11 and yes requested permissions were added.

**Comment by dubdabasoduba** [comment]
@madrinekariuki Sorry for the late reply can you try replicating the same using android 10? We haven't certified OpenSRP to run on android 11 yet.

**Comment by madrinekariuki** [comment]
@dubdabasoduba This is noted. Will share feedback once done.

**Comment by dubdabasoduba** [comment]
Asante!

**Comment by madrinekariuki** [comment]
@dubdabasoduba 
This has been tested on an android 10 devices. It is noted that the app is not crashing on the 2 instances mentioned above.

**Comment by madrinekariuki** [comment]
Issues reported above have been retested on an android device Version 10.

- both issues 1 $ 2 are now okay. 
- regression tests have also been done on the APK and have passed.


Test results can be found [here](https://ona.testrail.io/index.php?/runs/view/60&group_by=cases:section_id&group_id=118&group_order=asc)

Its good to note we have some scenarios that have not been tested yet

- tests around QR scan code.
- tests around cards (e.g reporting a lost/damaged card)
- tests on recording vaccines for children out of the catchment areas.

**Comment by dubdabasoduba** [comment]
@madrinekariuki Asante

**Comment by AnnieMungai** [comment]
Looks great!
