### ISSUE TITLE
Users on production not able to sync data

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#160]
**Describe the bug**
- [x] Users not able to sync data to the server. When the user tried to sync data to the server, a 'sync failed' error is thrown. 
- [x] The location hierarchy of some facilities is also not loading - it throws and error ' sync failed' error. 

**To Reproduce**
1. Log in with a user from a Health facilityon production (reach out to Anne for this). 
2. Observe how the app behaves after that. 

**Expected behavior**

**Screenshots**
Users should be able to log into the app and sync data. 
If there is more than 1 user in the facility and both users sync data, they each should see each other's data. 

**Additional context**
There was a redeployment to the server to OpenSRP version v2.8.35-SNAPSHOT on 6/7th Dec. This error was not present before this redeployment. @madrinekariuki kindly confirm this.

**Comment by madrinekariuki** [comment]
yes. on [this](https://github.com/opensrp/opensrp-client-unicef-tunisia/releases/tag/v1.0.0-release)  shared apk, sync was happening okay without any error the moment one logged in. 
@AnnieMungai

**Comment by dubdabasoduba** [comment]
@AnnieMungai please retest this after the fixes done on Thursday.

**Comment by AnnieMungai** [comment]
Looks good!
