### ISSUE TITLE
Feedback on the Production Dashboard

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#164]
Note! This feedback is for both French and English dashboards
1. The immunization given by antigen is pulling from data in 1973. This should only be showing data from Dec 2021 when the app went live. 
![image](https://user-images.githubusercontent.com/58034047/151710824-c06f4b86-56dc-4506-bdc5-cc9f507e6cf7.png)
2. On the same dashboard, the antigen columns should be grouped by the order at which they are given (by age) not by antigen sets - here is the [data dictionary](https://docs.google.com/spreadsheets/d/1tYvHOu3N9n2VWqZagq0na2BEag-0G7RCvWwqgjBX2vY/edit#gid=1827223928) with the antigens by age they are given: HepB 0, BCG, IPV 1, Penta 1, PCV 1, IPV 2, Penta 2, PCV 2, Penta 3, OPV 1, PCV 3, MR 1, VHA, DTP 4, OPV 2, MR 2 
3. On the same chart, the months and years are jumbled and not following the correct order: 
![image](https://user-images.githubusercontent.com/58034047/151711310-facc3d69-a432-42ad-80e6-b9540efd2fa1.png)
4. The HPB 0 and BCG charts are not pulling any data even though there are children that have received these vaccines and are seen on other charts. 
![image](https://user-images.githubusercontent.com/58034047/151711377-2cc49ae9-c6d7-441f-a407-d606cefd0dda.png)
5. Key activities chart not clear the activities its pulling.
![image](https://user-images.githubusercontent.com/58034047/151711438-6281dbf5-7d46-4e51-90c7-37e71b47e99e.png)
6. This chart would be more useful to the user if it was a bar chart vs a line graph (its on child registrations)
![image](https://user-images.githubusercontent.com/58034047/151711448-b126fdc0-bdc4-456b-a4a4-95974af8b9d4.png)

**Comment by muneneg** [comment]
@AnnieMungai 
- [x] 1. I have added a filter to show data from Dec 2021 to dat.
- [x] 2. I have changed the order. -- Are these (VHA, DTP 4)  being recorded in the app now? might need to add them 
- [ ] 3. This is a superset limitation. Other option would mean I add the Month Number to the label.
- [ ] 4. This one I will need to investigate further.
- [x] 5. The x-axis on this chart is the facility name, not activities. -- Should I remove the chart?
- [x] 6. I have changed the chart to a bar chart

**Comment by muneneg** [comment]
@AnnieMungai Seems like for BCG and HEPB0 the charts are not showing data because of the `ages` when the children got vaccinated. Most of them Got it way after the `0-59 days`. 

![image](https://user-images.githubusercontent.com/41571129/152757276-8e6bd03f-067a-4160-9e25-eb26656987bc.png)

**Comment by AnnieMungai** [comment]
> @AnnieMungai
> 
> * [x]  1. I have added a filter to show data from Dec 2021 to dat.
> * [x]  2. I have changed the order. -- Are these (VHA, DTP 4)  being recorded in the app now? might need to add them
> * [x]  3. This is a superset limitation. Other option would mean I add the Month Number to the label.
> * [ ]  4. This one I will need to investigate further.
> * [x]  5. The x-axis on this chart is the facility name, not activities. -- Should I remove the chart?
> * [x]  6. I have changed the chart to a bar chart

@muneneg 
On #2 - I believe the children being registered right now on the app are yet to get to the age to receive VHA and DTP4 but should receive these in the future. We should therefore be able to pull them.  Not sure whether we can add them as test data at the moment. 
On #5 - what happens if we turn this to a line graph vs a bar graph? That way we capture both the facility and the activities each facility has given.

**Comment by AnnieMungai** [comment]
> @AnnieMungai Seems like for BCG and HEPB0 the charts are not showing data because of the `ages` when the children got vaccinated. Most of them Got it way after the `0-59 days`.
> 
> ![image](https://user-images.githubusercontent.com/41571129/152757276-8e6bd03f-067a-4160-9e25-eb26656987bc.png)

On the BCG and HBV0 - the indicator should capture all children that have received these 2 vaccines despite the age -- It should **totals**.

**Comment by muneneg** [comment]
@AnnieMungai These changes have been implemented into the French dashboard, I will start on the English one soon.

**Comment by AnnieMungai** [comment]
@muneneg more feedback from the client. 
- [ ] (7)The Mother Rubella vaccines seem not to be computing the %. 
![image](https://user-images.githubusercontent.com/58034047/154035328-3b1ef3c2-f968-465c-b80c-a757121f2d6a.png)
- [ ] (8) Growth data not showing correct data (compare with the summary)
![image](https://user-images.githubusercontent.com/58034047/154035587-19d6310b-2bd0-4df3-837c-f7e849ea6429.png)

**Comment by muneneg** [comment]
@AnnieMungai see my responses in-line
> 
> * [ ]  (7)The Mother Rubella vaccines seem not to be computing the %.
>   ![image](https://user-images.githubusercontent.com/58034047/154035328-3b1ef3c2-f968-465c-b80c-a757121f2d6a.png)

The first column shows number of births and then the other columns check for different conditions. So there might be births but the other conditions were not met. The calculations are correct.
![image](https://user-images.githubusercontent.com/41571129/154053753-40bc8c84-9ef1-4325-a6c7-b64c6eee6a9c.png)


> * [ ]  (8) Growth data not showing correct data (compare with the summary)
>   ![image](https://user-images.githubusercontent.com/58034047/154035587-19d6310b-2bd0-4df3-837c-f7e849ea6429.png)

The summary shows total number of weights/heights measured but these charts check the number of times a child has been measured at that age. So same as above, I think the data in the system does not meet the conditions here.

**Comment by AnnieMungai** [comment]
@muneneg
1. Order the vaccines on this chart as they follow each other : HepB 0, BCG, IPV 1, Penta 1, PCV 1, IPV 2, Penta 2, PCV 2, Penta 3, OPV 1, PCV 3, MR 1, VHA, DTP 4, OPV 2, MR 2. Also change colour of the chart to blue (see chart on stage). 
![image](https://user-images.githubusercontent.com/58034047/155288572-8b8de47b-d481-4d6a-a0b8-8ec6fd29cc06.png)

2.

**Comment by AnnieMungai** [comment]
@muneneg closing this.
