### ISSUE TITLE
Rapidpro QA

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#166]
- [ ] QA the Tunisia Rapidpro production instance for an issue previously identified: https://github.com/onaio/rapidpro-support/issues/34 and https://github.com/onaio/rapidpro-support/issues/37

**Comment by faith-mutua** [comment]
@AnnieMungai issue [#37](https://github.com/onaio/rapidpro-support/issues/37) is currently failing with a `500 internal server` 
error on the console log when fetching contacts. See attached screenshot for more details

![Screenshot from 2022-03-02 16-11-57](https://user-images.githubusercontent.com/17847885/156370326-c27a30bb-c1c4-4abc-af16-4886f8d8f1cf.png)

**Comment by AnnieMungai** [comment]
@faith-mutua This issue was worked on: https://github.com/onaio/rapidpro-support/issues/37

**Comment by faith-mutua** [comment]
@AnnieMungai this issue has been resolved. closing it

**Comment by faith-mutua** [comment]
@AnnieMungai this has been resolved
