### ISSUE TITLE
Qa- Card support feature bug fixes

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#167]
Conduct on the UNICEF Tunisia Card support feature on the OpenSRP Web production instance: https://web.tunevacc.tn
(Credentials on bitwarden)
- [x] A user with the right credentials  (regional or national user) should be able to view the 'Data download' tab once logged on to the web. 
- [x] If they apply the all locations filter and enter the dates, they should be able to download a CSV file. On the file, there shouldn't be clients with empty facility_of_registration fields. 
- [x] If the location selected is a region, or district, any client data downloaded should not have blank facility_of_registration fields. 
- [x] If any of the other filters are applied, user should down a CSV with the data of the fields selected. 

Linked to these issues:
https://github.com/opensrp/web/issues/923

**Comment by faith-mutua** [comment]
@AnnieMungai all the issues listed above have been resolved. I have tested this using the `demo` user
