### ISSUE TITLE
Test the user login and Android 12 compatibility

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#169]
Test the following:
- Can upgrade from **Tunevacc 1.0.0 on play store** to the latest release. 
- User login issue indicated on this ticket: https://github.com/opensrp/support/issues/299
- App functionality when using Android 12 [might need to compare with functionality on Android 9]. 

**Latest release:**
https://github.com/opensrp/opensrp-client-unicef-tunisia/releases/tag/v1.0.2

**Acceptance Criteria**
- [x] User can upgrade from v 1.0.0 [downloaded from playstore] to v 1.0.2 on production
- [x] User can login with the correct credentials - test different variations of the same username: example: demo, Demo, dEMo etc. 
- [x] App functions as it should when on Android 9 and 12.
- [x] User can successfully complete sync.
- [x] No force closing on any of the forms.
- [x] No force closing when conducting any functionality in the app. 
- [x] User can successfully save a registration form. 
- [x] User can successfully conduct various tasks at the top right hand menu on a child's details page view. 

**Expected time of delivery**
2nd March 2023 - this contract time ran out and this is the last piece of work before we can close the contract.

**Comment by Mstjamush** [comment]
<img width="278" alt="Screenshot 2023-03-01 at 12 44 22" src="https://user-images.githubusercontent.com/29072646/222102457-64e734f9-bc14-4b27-8e57-cea8edd0eed4.png">

The key test to upgrade the App from v1.0.0 to v1.0.2 failed. See attached screenshot

**Comment by AnnieMungai** [comment]
@Mstjamush  v1.0.2.apk has been uploaded to the test track on playstore. You will have access when you log into your device with your test email creds.

**Comment by Mstjamush** [comment]
QA is complete. Works as expected
