### ISSUE TITLE
Implement app icon

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-unicef-tunisia#17]
- [ ] Implement the App icon - this icon will also be what is seen by the user when trying to download the app from the play store. The app icon to be used is the PNV logo.  Name of the app- TUNeVAC. 
NB! Full name of the app is Tunisie e-Vaccination. 
- [ ] The logos to be used are found [here](https://drive.google.com/drive/folders/1WgpW0GNpxCfP3Pt-8jgsoVh0yuCF1wNk).

**Comment by rowo** [comment]
Is that logo big enough?

**Comment by ellykits** [comment]
@rowo For Playstore we may need a bigger logo but here is how the one shared looks in a tab.

![Screenshot_1593179376](https://user-images.githubusercontent.com/26865532/85864583-604c1900-b7cd-11ea-9cf4-def2acbe7b32.png)

**Comment by AnnieMungai** [comment]
@rowo we definitely need a bigger logo to make the icon more visible.

**Comment by AnnieMungai** [comment]
Debug V.0.03 
The logo looks much better. If we get a better version we will replace the current one if necessary.
