### ISSUE TITLE
Implement Advanced search page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-unicef-tunisia#19]
- [x] Implement Advanced search. This option allows the user to search for a child client from both the facility records and from other facilities. The advanced search button is accessed through the [bottom navigation menu](https://github.com/OpenSRP/opensrp-client-unicef-tunisia/issues/3). When in advanced search function, the bottom navigation search button is active (blue). 
- [x] The search limits should be 1) Outside and inside my catchment area (requires internet connection 2) My catchment area ([refer to this issue](https://github.com/OpenSRP/opensrp-client/issues/407)). 
- [x] Search outside and inside my catchment area should work only if the device is connected to the internet. 
- [x] Advanced search parameters to use are [here](https://docs.google.com/spreadsheets/d/1HL2ekMnwC7YaE_2tcXXCwx2lExJMQ0k8gnw9FY-qUJ4/edit#gid=825408540). 
- [x] The advanced search page UI
![image](https://user-images.githubusercontent.com/58034047/85219267-0bfb0080-b3ab-11ea-8ffc-664924792236.png)
- [x] Taping on the Search buttons on an advanced search page opens the search results page: this shows the results found. 
![image](https://user-images.githubusercontent.com/58034047/85219519-246c1a80-b3ad-11ea-8af3-9e49e8841969.png)

**Comment by AnnieMungai** [comment]
@cafootitt the advanced search option updated.

**Comment by cafootitt** [comment]
@AnnieMungai This is looking good. Let's include implementation instructions for the search results page. What information is displayed? What actions are performed when each button is tapped?

**Comment by AnnieMungai** [comment]
@cafootitt highlighting this on a different issue #26.

**Comment by AnnieMungai** [comment]
Debug v.0.0.3

The search parameters are off. As indicated above, these are the correct [search parameters](https://docs.google.com/spreadsheets/d/1HL2ekMnwC7YaE_2tcXXCwx2lExJMQ0k8gnw9FY-qUJ4/edit#gid=825408540).

**Comment by AnnieMungai** [comment]
Parameters used for the advanced search are correct. 

Highlighting errors in the functionality on issue #40
