### ISSUE TITLE
Edit child registration details

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-unicef-tunisia#21]
- [ ] Edit child registration details on the registration form as [per this data dictionary](https://docs.google.com/spreadsheets/d/1_MTBjwwPfH1_e7uDqPkGS35VpDFhewIrwDF8Lq6xvSc/edit#gid=1439390423).

**Comment by AnnieMungai** [comment]
Debug v.0.03

Looks great!
