### ISSUE TITLE
Customize the log-in page

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#29]
Customize the log-in page for Tunisia.
- The page mock-ups are as below: (Images can also be found on slide 2 [here](https://docs.google.com/presentation/d/1AlJr0f6LXb-QCHv5nQjdO0AgDrNDMvGw/edit#slide=id.p2))
![image](https://user-images.githubusercontent.com/58034047/86210340-1d979180-bb7d-11ea-9335-fc1553fd6817.png)

- Logos used can be found [here.](https://drive.google.com/drive/folders/1bwbd2Xq2gp0ltgixuIT_zaZN3Mtk8INy)

**Comment by ellykits** [comment]
@AnnieMungai Here is the customized login page screenshot.
![Screenshot_1593773686](https://user-images.githubusercontent.com/26865532/86462765-d48a3d80-bd34-11ea-8e66-c57873d76032.png)

**Comment by AnnieMungai** [comment]
v. 0.0.3 

Looks good.
