### ISSUE TITLE
Implement calculation for additional PCV for premature babies

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#30]
- [x] Implement additional PCV calculation for preterm babies on the data dictionary [[here](https://docs.google.com/spreadsheets/d/1_MTBjwwPfH1_e7uDqPkGS35VpDFhewIrwDF8Lq6xvSc/edit#gid=1439390423)] - row 22.

**Comment by cafootitt** [comment]
@AnnieMungai The calculation is missing in the data dictionary. Can you please add it?

**Comment by AnnieMungai** [comment]
@ellykits I will circle back to this once the Pre-term vaccines are completed.

**Comment by AnnieMungai** [comment]
App ver 0.0.5- debug (24th July 2020).

LGTM!
