### ISSUE TITLE
Implement the Record Out of Catchment Area Form

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#31]
- [x] Implement the Record out of catchment form as per the data dictionary [here.](https://docs.google.com/spreadsheets/d/1Uoqi6FmXpF0b4i-BDWxw417TeLnTmAIoVHOiTq4PhZ0/edit#gid=580548781) 
- [x] The Unique ID will auto-populate with the child's system ID (OpenSRP) when the user scans card (see issue #25) 
- [ ]  Submitting the record will sync the data submitted with the child's facility.

**Comment by ellykits** [comment]
@AnnieMungai Can we track the remaining work for this issue separately since it is linked to Card Support.

**Comment by AnnieMungai** [comment]
debug-v0.1.5
-Scan QR code works perfectly. 
-Still not syncing data filled on out of catchment area. Moving this issue to #98
