### ISSUE TITLE
Implement the Adverse Effects Form

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#33]
- Customize the adverse effects form from the child's profile based on [this data dictionary](https://docs.google.com/spreadsheets/d/106-np911xfDGUx7RpF_GdOIER4bcMHnASCCO3dlep6A/edit). The Json file can be found [here](https://drive.google.com/drive/folders/1DTeb5_Bea7ZDomArW9nSTKRkbcpPFY5S). 
![image](https://user-images.githubusercontent.com/58034047/88531776-0d53c480-d00c-11ea-94b8-e9a0ae79caf4.png)

**Comment by AnnieMungai** [comment]
V.0.0.6 
The form flows quite nicely. 
However, there are some minor issues:
- [ ] Some of the vaccines are displaying in small caps. They should look like the vaccines on the schedule or other parts of the app. 
![image](https://user-images.githubusercontent.com/58034047/89269294-63df8500-d642-11ea-9e0b-3961fcbae3b1.png)
- [ ] The dates picker on the form can go beyond the date that the child was born. These dates should work like the other dates within the app - should not be able to scroll beyond the child's date of birth. 
![image](https://user-images.githubusercontent.com/58034047/89269650-d6e8fb80-d642-11ea-9488-9a04d23266fd.png)
- [ ] The logic on when to open the details of the vaccine e.g lot number is off. The form for the vaccine details should open when the HF name is given. Refer to the data dictionary- highlighted in yellow. 
![image](https://user-images.githubusercontent.com/58034047/89270687-6511b180-d644-11ea-8637-87c0a24fd218.png)

- [ ] Change the responses on the type_care question to select one - highlighted in yellow on data dictionary.

**Comment by ellykits** [comment]
Fixed bugs
![Screenshot_1596545965](https://user-images.githubusercontent.com/26865532/89296776-7f12ba80-d66b-11ea-96e0-dee824fc03a5.png)
![Screenshot_1596545922](https://user-images.githubusercontent.com/26865532/89296784-820dab00-d66b-11ea-8294-f4fa8260dd1a.png)

**Comment by AnnieMungai** [comment]
V. 0.0.6r2
Looks great!
