### ISSUE TITLE
Standardised Read ME doc

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-client-unicef-tunisia#34]
OpenSRP projects Read Mes are required to follow [this template](https://github.com/onaio/opensrp-tasks/blob/master/README.md.template)

**NB:** The sections required for update are those with angle brackets on the template

**Comment by AnnieMungai** [comment]
UNICEF Tunisia is a child immunization digital project: it is a child health module. This module's key features include: Child registration (birth and death), growth monitoring with 3 z-scores, immunization schedules, health card support. The module is supported in 3 languages; English, French and Arabic.
