### ISSUE TITLE
Change the name of the app on the side menu

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#37]

**Comment by ellykits** [comment]
@AnnieMungai  this has been updated. ![Screenshot_1594113900](https://user-images.githubusercontent.com/26865532/86759035-f04f5580-c04c-11ea-8175-dcfbf72a392b.png)

**Comment by AnnieMungai** [comment]
@ellykits I will QA this on the next release.

**Comment by AnnieMungai** [comment]
Looks good!
