### ISSUE TITLE
Implement In-app Reports

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#38]
- [ ] Implement in-app reports as per [this](https://docs.google.com/spreadsheets/d/1MdQvZ1VirLGqgNwxpBPvFmVfA7HQT-gWrMXWOoDxyIA/edit#gid=571946050) data dictionary. #51 and #52

**Comment by cafootitt** [comment]
This is a bit redundnat, so closing. This information is included in the other reporting issues.
