### ISSUE TITLE
Implement child registration form

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#4]
- [x] Implement a child registration form as on [this](https://docs.google.com/spreadsheets/d/1_MTBjwwPfH1_e7uDqPkGS35VpDFhewIrwDF8Lq6xvSc/edit#gid=1439390423) data dictionary. 
- [x] The registration form is accessible from 1 point on the home page: the [bottom navigation](https://github.com/OpenSRP/opensrp-client-unicef-tunisia/issues/3), the *add child* icon: tapping on this icon will open the registration form. 

- [x] Once the registration form is completed and submitted, the child's record appears on the child register. A newly registered child will appear at the top of this register.

**Comment by cafootitt** [comment]
@AnnieMungai Once the child is registered, does the user land on the main register page or the child's profile page? What does the Malawi app do?

**Comment by AnnieMungai** [comment]
@cafootitt the app redirects back to the main register page once a child's registration is submitted.

**Comment by AnnieMungai** [comment]
19 June version
The registration form can be accessed from the top and bottom navigation.  (looks good)
Once registration form is submitted user redirected to the register home page and newly registered child is at top of register (looks good).

The registration form has not been customized as per Tunisia data dictionary.

**Comment by AnnieMungai** [comment]
@ellykits based on discussions with @rowo, the add child willing only be at one point to make it easy for the health worker to use the app. This means the add child button will only be at the bottom navigation.  I am revising the issue to reflect these changes.

**Comment by AnnieMungai** [comment]
debug. v 0.03

Looks good.
