### ISSUE TITLE
Implement the In-app reports UI

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#50]
- [x] The In-app reports are accessible from the side menu as shown.

![image](https://user-images.githubusercontent.com/58034047/92327309-637f4300-f061-11ea-8396-658807896453.png)

- [x] Tapping on the reports will open 2 options: 
- Immunization and growth monitoring monthly reports
- Annual coverage reports
![image](https://user-images.githubusercontent.com/58034047/92435249-86693e80-f1aa-11ea-8fd3-1f53fd75dce4.png)

- [x] If the user taps on the **Immunization and growth monitoring monthly reports**, they are directed to the page with the same name. #51 

- [x] If the user taps on **Coverage reports**, they will be redirected to the Coverage rate reports page. #60

**Comment by cafootitt** [comment]
Ok, done reviewing, this issue is good to go.

**Comment by AnnieMungai** [comment]
debug-v0.1.2

Looks good.
