### ISSUE TITLE
Implement the Sent Monthly Reports View

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#52]
- [x] The **sent monthly** is the tab that the user lands on when selecting the **Sent Monthly** tab from the Immunization and growth monitoring monthly reports view

- [x] Sections are created for each calendar year: For example 2019, 2020, 2021 etc with the calendar years appearing in reverse chronological order - the most recent year appears first/at the top. 

- [x] Underneath each year section, the sent monthly reports appear for the months they were sent [month in words, year]. The date shown below the report month name is the date the report was confirmed and sent, and the user that submitted the report.

![image](https://user-images.githubusercontent.com/58034047/94530942-7d690b80-0244-11eb-941d-14178f5501c5.png)

Note! There is a need for a different icon for the reports. 

- [x] Tapping on a specific month opens the report from that month, in read-only format.

![image](https://user-images.githubusercontent.com/58034047/94531012-94a7f900-0244-11eb-91f5-e6188c2314a2.png)

- [x] Each of the above sections is expandable or collapsible by tapping on the carrot icon to the right of the section header.

**Comment by cafootitt** [comment]
@AnnieMungai I reviewed and simplified some things. Some instructions like the navigation between the tabs and the side menu navigation is a bit redundant with the other issues, so I've removed to simplify. The report they're opening is the same report, same format, etc. as when they filled in and submitted the report. Just wanted to clarify that. We're not building a new view of the report page for this. 

Please include the new icon for the report, so this issue is complete.

**Comment by AnnieMungai** [comment]
@rowo Please help us get an icon that we can use for the reports on this issue.

**Comment by rowo** [comment]
@AnnieMungai here are generic report icons as discussed on Slack. The second is the daily tally icon I believe.

![report01](https://user-images.githubusercontent.com/1584163/95082018-6f096c80-06e8-11eb-903f-506e5938c580.png)

![report02](https://user-images.githubusercontent.com/1584163/95082023-703a9980-06e8-11eb-8d32-ec032b834205.png)

**Comment by ellykits** [comment]
@AnnieMungai Are we using the UI mockup above to show the indicators summary? @cafootitt Can you point to the existing UI you are referring to? Because I have seen this view different in 2 project (GIZ Malawi/WellnessPass)

**Comment by AnnieMungai** [comment]
> @AnnieMungai Are we using the UI mockup above to show the indicators summary? @cafootitt Can you point to the existing UI you are referring to? Because I have seen this view different in 2 project (GIZ Malawi/WellnessPass)

@ellykits the issue was edited to include the issue raised. Please use the first icon for the sent monthly reports. We are using the UI as above, with the new icon.

**Comment by ellykits** [comment]
Noted thanks @AnnieMungai . Just to be clear on this - this is a new UI as far as I know. I will proceed with the implementation.

**Comment by cafootitt** [comment]
@ellykits This is the same UI for the most part from ZEIR.

**Comment by ellykits** [comment]
@cafootitt @AnnieMungai Here is the new implementation with collapsible report headers
![Screenshot_20201102_234448](https://user-images.githubusercontent.com/26865532/97917469-909c5900-1d65-11eb-9145-1b1fa5c59f8c.png)

**Comment by cafootitt** [comment]
Looks good!

**Comment by AnnieMungai** [comment]
debug-v0.1.2
Sent reports are working as they should.
