### ISSUE TITLE
MLS Missing strings

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#56]
- [x] Some months on the register page not showing translations - both french and arabic.
![image](https://user-images.githubusercontent.com/58034047/93350099-ef9f2080-f840-11ea-876c-ed064b2b5a6d.png)
- [ ] Months and some vaccines on the child vaccine history page not translating - both french and arabic - missing on Transifex files. 
![image](https://user-images.githubusercontent.com/58034047/93350189-09406800-f841-11ea-8551-8c50f70b9c8f.png)
- [x] Adverse effects page - Header not translating (was also missing from the strings file)- both french and arabic.
![image](https://user-images.githubusercontent.com/58034047/93350286-2412dc80-f841-11ea-8011-e41f8c947096.png)
- [x] Child registration details strings not translating (I think this was the untranslated content-to confirm once the new translations are added to the app). 
![image](https://user-images.githubusercontent.com/58034047/93350446-545a7b00-f841-11ea-8c75-cecb34d554e0.png)
- [x] Some months on the vaccine page not translating - both french and arabic
![image](https://user-images.githubusercontent.com/58034047/93350639-8835a080-f841-11ea-9c9c-9dc2a3cde4e9.png)
- [ ] Archive child strings on child status (on child's profile) missing on Transifex. Add these to transifex for translations.
![image](https://user-images.githubusercontent.com/58034047/93351138-03975200-f842-11ea-8b5b-d7897ab49e19.png)

**Comment by ellykits** [comment]
@AnnieMungai All the translations here apart from **Adverse Effects** should be done on the child library. The code with the strings is now merged. Since child is a core module used in more than one project, it makes sense to translate them for everyone on child library project on transifex.

**Comment by ellykits** [comment]
Adverse effect for tiitle tranlation fixed ![Screenshot_1601037094](https://user-images.githubusercontent.com/26865532/94267403-35946c80-ff44-11ea-9379-3154dd87f308.png)

**Comment by AnnieMungai** [comment]
preview-v0.1.0.apk
@ellykits Most of the translations are still not done.
- [ ] I think there are some files that have not been pulled from Transifex such as the dynamic vaccines file. 
- [ ] Also, some translations are already done on the child core library are not updated on this version. Example - the name of the months in French.

**Comment by AnnieMungai** [comment]
debug-v0.1.1

Looks good. 

The pending translations on the child master library being worked and can be merged once they are completed.
