### ISSUE TITLE
Implement Annual Coverage Reports

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#60]
Coverage reports are generated based on annual numbers of children vaccinated for a particular vaccine dose compared to the target population: i) children under 1 and, ii) children 1-2 years. The target population number is sent from the National level to the health facility. The health facility worker will therefore have to key in the target population numbers for a specific year to complete the annual coverage reports (see workflow diagram [here ](https://docs.google.com/document/d/1HyfXRzzl1PJkCPC785XeqKUz2vEu_qOZGduHdcy5SvU/edit#heading=h.mbki5nx7ktae)and related reporting dictionary [here](https://docs.google.com/spreadsheets/d/1MdQvZ1VirLGqgNwxpBPvFmVfA7HQT-gWrMXWOoDxyIA/edit#gid=571946050)). Also refer to [this ](https://github.com/OpenSRP/opensrp-client-path/issues/174), [this](https://github.com/OpenSRP/opensrp-client-path/issues/173) and [this](https://github.com/OpenSRP/opensrp-client-path/issues/172) issue. 

- [x] The annual coverage reports are accessible from the side menu #50 
- [x] The user lands on the coverage report page (see below) with the current year selected (e.g. 2020).  The Year field at the top is a dropdown, where the user can select which calendar year to view. Only 2020 will be an option for now. On January 1, 2021, 2021 should get added to the dropdown.
- [x] When the current year is selected in the dropdown, the "in progress" status is shown in parentheses. 
- [x] The user can select other years from the dropdown, if available.
- [x] If it is the first time the user is viewing the report for that year, they will be prompted to enter the annual target population numbers for that facility both for under 1s and 1-2-year-olds. This will be in form of a pop-up on the screen with the following texts: (similar to [this issue](https://github.com/OpenSRP/opensrp-client-path/issues/172))
*Set under 1year target population - [year]*
*Set 1-2year target population - [year]*
@ellykits we can discuss whether this is the best way to approach this or whether 2 different pop-ups would work better. 
![image](https://user-images.githubusercontent.com/58034047/94653528-62f66700-0304-11eb-88cb-2f78a940db92.png)

- [x] Upon entering the target population numbers, the coverage rates for each of the vaccine doses get calculated immediately and are displayed.
![image](https://user-images.githubusercontent.com/58034047/94538791-2287e200-024d-11eb-9eb6-c645c10e9d22.png)

- [x] Tapping "OK" saves the input number and it updates the target population number (for that particular calendar year). 
- [x] Tapping "Cancel" or tapping anywhere outside the window closes the window without saving the changes.
- [x] If the user does not input the target population numbers, the coverage rates will not be viewable. An error message will show instead that reads: **Error: No target**. 
![image](https://user-images.githubusercontent.com/58034047/94656522-d7cba000-0308-11eb-9db9-0e2314d892f2.png)

- [x] The user is able to edit the target population numbers by tapping on the edit icon next to them. If the target population numbers change, the coverage rates are re-calculated and updated immediately on the list.
- [x] The coverage report numbers are finalized on the first day of the following calendar year. E.g. the 2020 coverage report becomes finalized on Jan 1, 2021. On this date, the "in progress" status drops from the year 2020 in the dropdown, and the new calendar year, "2021 in progress", appears as an option in the dropdown.
- [x] Coverage rates are blue for the completed years.
![image](https://user-images.githubusercontent.com/58034047/94656614-f6319b80-0308-11eb-82e5-24c87d62f718.png)
- [x] Years are sorted in reverse chronological order in the dropdown, e.g. 2020, 2019, 2018, etc.
- [x] The target population numbers are stored offline on the device so that the user does not need to re-enter target population numbers each time they view that year's report.

**Comment by cafootitt** [comment]
@AnnieMungai @ellykits We need to discuss how the reports are going to sync, how frequently, etc. Let's discuss in the next standup. Just adding a note here to flag this to everyone.

**Comment by cafootitt** [comment]
Reviewed, issue looks good to me.
I think we decided to sync these reports monthly?

**Comment by AnnieMungai** [comment]
@cafootitt this is correct. The reports will be synced monthly.

**Comment by ellykits** [comment]
> we can discuss whether this is the best way to approach this or whether 2 different pop-ups would work better

@AnnieMungai with regards to :point_up_2: I agree it is okay to set the targets in one popup for better UX. @cafootitt @AnnieMungai  I have noticed that Unicef Tunisia has 2 targets (for Under 1 and 1-2 years). From the design it is not quite clear which target the coverage rates are computed for:
1. Does this mean that the coverage computation is for both targets?
2. If we generate reports for the targets separately should we sync them as 2 separate events? (One for Under 1 target and the other for 1-2 yrs target)

With the assumption that we generate separate annual coverage reports for the 2 targets, I would suggest we include a dropdown for selecting  target (like the dropdown for selecting the year) - the rest of the UI should remain the same. The coverage rates will then be calculated depending on the selected target. (This approach would be more extensible in the event that the client decides to add  more target populations or when this feature is required in a project with population targets other than Under 1 and 1-2 years), @rowo can weigh in on this.

**Comment by cafootitt** [comment]
@ellykits Hi Elly - good questions. I'll let Anne respond tomorrow, but each coverage indicator only needs to be calculated once - some vaccines use the under 1 while some vaccines use the 1-2 year old target. Which one they use is based on when the vaccine is given - in the first year or second year of life.

**Comment by AnnieMungai** [comment]
Looks good.
