### ISSUE TITLE
Dyncamic Vaccines events not Processed with new Installs

### ISSUE THREAD

**Issue by ellykits** [OpenSRP/opensrp-client-unicef-tunisia#64]
There is a bug with processing dynamic vaccines events for fresh installations. Repercussion of this is allowing users to record vaccines greater than the required number (10).

**Comment by AnnieMungai** [comment]
debug-v0.1.1
Dynamic vaccines added, however, the count is exceeding 10 vaccines in total. The vaccines should be a maximum of 10 per child.

**Comment by ellykits** [comment]
This is now fixed.

**Comment by AnnieMungai** [comment]
V. 0.1.4.3-r4
Can now only record 10 vaccines! Great!!
