### ISSUE TITLE
Implement child death registration

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#7]
- [ ] Implement the death registration form as on [this data dictionary](https://docs.google.com/spreadsheets/d/1_MTBjwwPfH1_e7uDqPkGS35VpDFhewIrwDF8Lq6xvSc/edit#gid=1439390423) 
- The death registration form can be opened from the child profile top right navigation - Report deceased option. 
![image](https://user-images.githubusercontent.com/58034047/84860034-f918c100-b076-11ea-92c6-2ae31b4fee13.png)

- Tapping on this option will open *report death* form. 
- The form once filled and submitted will archive a child's record.

**Comment by cafootitt** [comment]
@AnnieMungai Let's also include details on where the form is located, how the user opens the form and also what happens when the form is submitted.

**Comment by AnnieMungai** [comment]
This is done and the issue is ready for engineering now.

**Comment by AnnieMungai** [comment]
Debug v: 0.0.1 (19th June)
Form not aligned to the Tunisia data dictionary. Edit required- Remove causes of death.

**Comment by AnnieMungai** [comment]
App ver: 0.02-debug

Looks good.
