### ISSUE TITLE
Switching between the MLS options problem

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#71]
debug-v0.1.1

- [x] App not switching from Arabic to English, you have to switch it to French then to Arabic. User should be able to switch from Arabic to English directly. Switch to French and back is working okay.

**Comment by ellykits** [comment]
This has been resolved but not perfect. There are some inconsistencies  with Left to Right/Right to Left alignment of texts when switching to/from Arabic to English. This requires more time to figure out the cause of the inconsistencies

**Comment by AnnieMungai** [comment]
V. 0.1.4.3-r4 (demo3-using a tablet)

I noted the inconsistencies in some areas. I will leave this as not complete until they are sorted. Like here when I changed the device to French from English, it didn't pick. Arabic however picked. 
![image](https://user-images.githubusercontent.com/58034047/100106266-68da7580-2e79-11eb-9387-1141558d55cd.png)

**Comment by AnnieMungai** [comment]
debug-v0.1.5-r2

Looks good!
