### ISSUE TITLE
Complete Report Queries 

### ISSUE THREAD

**Issue by ellykits** [OpenSRP/opensrp-client-unicef-tunisia#78]
I separated the Reporting Queries from UI work. I will use this issue to track the SQL queries implementation based on the [data dictionary](https://docs.google.com/spreadsheets/d/1MdQvZ1VirLGqgNwxpBPvFmVfA7HQT-gWrMXWOoDxyIA/edit#gid=571946050)

**Comment by AnnieMungai** [comment]
Done. Looks good.
