### ISSUE TITLE
Add Card Support on side Menu

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#79]
- [ ] Add **Card Support** component on the left-hand side navigation, on OpenSRP Web page. 
- [ ] Tapping or clicking on **Card Support** will open the *Card support* home screen. 
Note! Only users at the Regional level will have access to the Card support option. 

Required: Mock-up for the card support on side navigation on OpenSRP Web. cc @rowo

**Comment by rowo** [comment]
@AnnieMungai What is card support?

**Comment by AnnieMungai** [comment]
@rowo I will be closing this issue as it has been addressed elsewhere on issue #80
