### ISSUE TITLE
Implement Card Support page home screen and functionality

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#80]
- Scope document for this can be found [here](https://docs.google.com/document/d/1pgraaDtGpuyjI9V9ytbTs4WXHo_goG5dinDK1XpLGBg/edit#). 
- [ ] On the Card support home screen, have options to filter data by:
       i) Filter by Location
       ii)Filter by Card status
       iii) Filter by Date range
- [ ] Have option to **Download CSV**. 

- [ ] **Filter by location**: When filtering by Location, the user should be able to select any facility in the region based on the location hierarchy of the country. The highest level of the location should be the region the user is assigned (Tunisia location Hierarchy: Central/National>>Regional>>District>>Health Facility).
- [ ]  If no location is selected in this filter, it defaults to all. 
- [ ] **Filter by card status**: When filtering by card status, the user should be able to select 2 different card status: **Needs card** and **Does Not need Card**. 
- [ ] If user selects **Need Cards** option,  clients with cards status _needs_card_ are selected. 
- [ ] If user selects **Does not need card** option, clients with card status _does_not_need_card_ are selected.  
- [ ] If no card status is selected, the default should apply (all records are selected). *** Need to confirm this functionality). ***
- [ ] *Filter by date range*: When filtering records by date range, user should be able to select from a date range. A date cannot be in the future. 
- [ ] If the user does not select a date range: then the **Download CSV** will be in a disabled state until that is filled in. That should show a hove message to tell the user that information.
- [ ] Downloading CSV file: When user taps on **Download CSV**, the file is downloaded based on the filters applied.
- [ ] The downloaded CSV file name should be named based on the date of the download, date range used in the filter, and location selected Example: Children_list_nairobi_west_20_10_2020_( 04-10-2020 - 19-10-2020).csv. 
- [ ] The downloaded CSV file will contain the following columns:
- IDV number (identifier/ OpenSRP number)
- Date of birth (dd/mm/yyyy)
- Child first name
- Child last name
- Child gender 
- The facility of registration/ location
- Date of registration
- Card Status
- Card status last update date

**Comment by dubdabasoduba** [comment]
@moshthepitt do we have custom confirmation dialogs for OpenSRP web or we will just use the javascript confirmation dialog. How much work is it to add the custom confirmation dialog?

**Comment by moshthepitt** [comment]
@dubdabasoduba should be pretty straight-forward using something like [sweetalert](https://github.com/t4t5/sweetalert)

**Comment by rowo** [comment]
@dubdabasoduba @moshthepitt I'm not sure how Ant works with what you are doing, but Ant has some nice dialogs with [popconfirm](https://ant.design/components/popconfirm/) and [modal](https://ant.design/components/modal/)

**Comment by rowo** [comment]
@dubdabasoduba @AnnieMungai Here's a proposal mockup for this page: [https://marvelapp.com/prototype/5394j2g/screen/74215563](https://marvelapp.com/prototype/5394j2g/screen/74215563)

![Download Client Data](https://user-images.githubusercontent.com/1584163/98173409-14b72380-1ec1-11eb-8b99-f2f783b5035e.png)

### Comments
1. Mentioned in the previous comment = I don't think a confirmation is necessary but I might be missing something.
2. Location defaults on all. Card status defaults on all.
3. Open question if what's labelled "card order" date is defaulted on anything such as end date as today. Maybe safest is to not default on anything.
4. If the date range isn't filled in, then the download csv will be in a disabled state until that is filled in. That should show a hove message to tell the user that information.
5. For labeling, I'm not sure about the card "order" wording and if that makes sense for the situation.
6. I wonder if the "needs card" language could be improved based on whether cards are scanned right after printing or when delivered.

**Comment by AnnieMungai** [comment]
@rowo the cards will be scanned at the HF when the client receives them. 
On 5: I have aligned the language to be concise and consistent across the board based on the card status.

**Comment by rowo** [comment]
@AnnieMungai Might be up to you and team to finalize if anything should change here on above or the Marvel comments. I think I'm at the limit of my recommendations without having been in client meetings.

**Comment by rowo** [comment]
@AnnieMungai Might be up to you and team to finalize if anything should change here on above or the Marvel comments. I think I'm at the limit of my recommendations without having been in client meetings.

**Comment by kelvin-muchiri** [comment]
@dubdabasoduba @AnnieMungai What should happen if there is no data returned?

**Comment by AnnieMungai** [comment]
@kelvin-muchiri you mean like there are no existing records based on the filters applied? We can indicate _**empty list**_, but I would like to hear what @dubdabasoduba thinks.

**Comment by AnnieMungai** [comment]
Looks good!
