### ISSUE TITLE
Implement Card Statuses

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#82]
For card support, there are 2 card status: **needs_card** and **does_not_need_card** status. 

When & How to set the **needs_card** status
- [x] This status will be set on the Child Client JSON object. An example can be found [here (https://github.com/OpenSRP/opensrp-client-unicef-tunisia/issues/55)
- This status can only be set during these two scenarios: 
1. During a new registration
2. After a card is reported lost or damaged on the child profile #13 
- [x] The Report lost or damaged card menu item is disabled the moment the card status changes to **needs_card**.
- [x] When the status is **needs_card**, change the Report lost or damaged card menu text: Card ordered: the date the card status changed. e.g Card ordered: 14-05-2020. 

When & How to set the **does_not_need_card** status
- [x] This status will be set on the Child Client JSON object. An example can be found [here (https://github.com/OpenSRP/opensrp-client-unicef-tunisia/issues/55)
- This status can only be set during this scenario: 
1. After the card is scanned during the search through the scan QR code functionality. 
- [x] When the status is **does_not_need_card**, the menu text goes back to Report lost or damaged card

**Comment by dubdabasoduba** [comment]
location hierarchy endpoint: https://opensrp-stage.smartregister.org/opensrp/rest/location/hierarchy/{location-uuid}?is_jurisdiction=true 
Clients endpoint: https://opensrp-stage.smartregister.org/opensrp/rest/client/search?attribute=card_status:status&registration_location={location-uuid}

**Comment by kelvin-muchiri** [comment]
Is the filter for the date range available?

**Comment by kelvin-muchiri** [comment]
I have a couple of questions:

1. What about the date range query params for the start date and end date?
2. What will the URL be like if I would want to make a request for multiple card statuses e.g I would to both those who need card and those who do not need card?

**Comment by ellykits** [comment]
@dubdabasoduba @kelvin-muchiri The search endpoint was updated to this https://unicef-tunisia-stage.smartregister.org/opensrp/rest/client/search?attribute=card_status:needs_card&locationIds=e2b4a441-21b5-4d03-816b-09d45b17cad7

>NOTE: you can pass a list of comma separated location ids also update the card_status accordingly

**Comment by AnnieMungai** [comment]
debug-v0.1.5
Looks good.
