### ISSUE TITLE
Filter filtering even archived records

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#87]
V.0.1.3-debug; User- Demo2
- [x] When filtering due and overdue services on home page, list of archived records shows. 
- [x] Record of all archived and deceased children shows after clearing the filter. This however disappears after a few moments. Note! The list should not be showing at all!

**Comment by ellykits** [comment]
This is resolved.

**Comment by AnnieMungai** [comment]
V. 0.1.4.3-r4

Looks good. Will raise an issue with archiving on a different issue.
