### ISSUE TITLE
Add question on the child registration on SMS language preference

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#90]
- [x] Add the SMS language preference on the [[registration form](https://docs.google.com/spreadsheets/d/1_MTBjwwPfH1_e7uDqPkGS35VpDFhewIrwDF8Lq6xvSc/edit#gid=1439390423)] (highlighted in purple)

**Comment by cafootitt** [comment]
@AnnieMungai why would we do this in the app and not in RapidPro? Wouldn't it be easier to do in RapidPro?

**Comment by AnnieMungai** [comment]
@cafootitt from what I undersatand, this is easier from the app-end.

**Comment by AnnieMungai** [comment]
@cafootitt @ellykits from the discussions with client, we shall proceed with adding the question on the registration form.

**Comment by AnnieMungai** [comment]
debug-v0.1.5-r2
Looks great!
