### ISSUE TITLE
Add daily tallies on the reporting

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-unicef-tunisia#91]
- [ ] Add daily tallies to the reports.

**Comment by cafootitt** [comment]
This is a significant addition. Why/how did this come up? Did the client request this?

**Comment by AnnieMungai** [comment]
Yes, I agree this is a significant change mainly because the requirements were for the monthly reports. It was suggested during the training today. However, it will require further discussion with the client, and also within ourselves.

**Comment by AnnieMungai** [comment]
@ellykits as discussed, this could be borrowed from the ZEIR implementation at a minimum LOE.

**Comment by AnnieMungai** [comment]
V.0.1.7- June release.

Looks good!
