### ISSUE TITLE
Sync taking awhile to complete

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-unicef-tunisia#95]
V.0.1.4.3-r4 (user- demo)

- [ ] Sync is taking a while to complete even when there are few records.

**Comment by ellykits** [comment]
I am unable to reproduce this @AnnieMungai. May have been an issue with your internet connection. Can you please provide more information on how I can reproduce this. Thanks.

**Comment by AnnieMungai** [comment]
@Mstjamush were you able to trst this? I wanted to be sure it is not only on my end that this was occurring.

**Comment by Mstjamush** [comment]
@AnnieMungai let me retest and revert

**Comment by AnnieMungai** [comment]
@Mstjamush did you test this issue? Seems it is still occurring.

**Comment by Mstjamush** [comment]
@AnnieMungai I did. Sorry I didn't update the feedback here. It is happening

**Comment by AnnieMungai** [comment]
@Mstjamush how long did it take to sync all the records currently in the app?

**Comment by Mstjamush** [comment]
@AnnieMungai I didn't make to. sync all the clients. But was just above 5000 in four and half hours

**Comment by AnnieMungai** [comment]
To check the enhamcements made on the Malawi app to see whether they can be implemented on Tunisia.
