### ISSUE TITLE
Advanced search not returning local searches when not connected to the internet

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia#97]
debug-v0.1.5
- [x] Advanced Search only working when connected to the internet. 
- [x] When not connected to the internet, the search not returning local searches even when the child is active in the register. 
- [x] Not able to select **my catchment area only** on the advanced search.

**Comment by ellykits** [comment]
I have not been able to reproduce this issue @AnnieMungai. My observation however is remote search is not returning correct result when the device has stayed offline for a long time (more than 5 hours), in this case, when the user logs out and login afresh the search work. The explanation for the failure in search would be expiration of access token that is refreshed when the user re-login.

**Comment by AnnieMungai** [comment]
@ellykits this is still an issue.

How replicate.:
Log in to the device and sync records. 
Turn off the internet and navigate to the advanced search. 
Select the *my catchment area only* on the search limits. Observe. 
Type in the first name of a child on the register. And conduct a search. Observe.

**Comment by AnnieMungai** [comment]
debug v.0.1.6

Looks great!
